[package]
name = "ophilia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
async-trait = "0.1.77"